 a=int(input("입력 1 : "))
  b=int(input("입력 2 : "))
  result =a+b
  print(a, "+" , b , "=" ,result)
  result=a-b
  print(a,"-",b,"=",result)
  result=a*b
  print(a,"*",b,"=",result)
  result=a/b
  print(a,"/",b,"=",result)